name: 'Push Helm Chart'
description: Create and push Helm Chart to Repository if helm folder exists
inputs:
  repository:
    description: 'Github repository name'
    required: true
  token:
    description: 'Github Token to access repository'
    required: true
  username:
    description: 'Github Username to access repository'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "helm/values.yml"
    - name: set repo url
      shell: bash
      run: |
        echo "GCR_IMAGE=oci://ghcr.io/${{ inputs.repository }}" >> $GITHUB_ENV
    - id: lower-repo
      shell: pwsh
      run: |
        "::set-output name=repository::$($env:GCR_IMAGE.ToLowerInvariant())"
    - name: Push Helm chart
      if: steps.check_files.outputs.files_exists == 'true'
      uses: bsord/helm-push@v4.1.0
      with:
        useOCIRegistry: true
        registry-url:  ${{ steps.lower-repo.outputs.repository }}
        access-token: ${{ inputs.token }}
        username: ${{ inputs.username }}
        force: true
        chart-folder: helm
        add-repositories: true